name: Analyze Flutter Code
on:
 pull_request:
  branches:
   - main
jobs:
 test:
  name: Analyze Flutter Code
  runs-on: ubuntu-latest
  defaults:
   run:
    working-directory: ./app
  steps:
   - uses: actions/checkout@v3
   - uses: subosito/flutter-action@v2.3.0
     with:
      flutter-version: '3.19.5'
   - name: Install packages
     run: flutter pub get
   - name: Gen localizations
     run: flutter gen-l10n
   - name: Run build_runner
     run: dart run build_runner build --delete-conflicting-outputs
   - name: Linter
     run: flutter analyze